spring:
  cache:
    type: simple
    cache-names:        # This 'cache-names' can limit the name spaces for Cache. If this property doesn't exist, it will allow all. If exist, only the listed names will be allowed to cache
    - post-single
#  redis:
#    host:
#    port:
## Above two properties(host, port) are needed if ablove spring.cache.type is 'redis'.
logging:
  level:
    org.springframework: INFO
    brian.boot.example.cache: DEBUG
  file: logs/spring-boot-logging.log
  pattern:
    console: 